// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmSzScrIQE2x6qmvmG7i_B3nTs7hskSO4',
    appId: '1:106683741204:web:bce2f0705f79cd4ca76301',
    messagingSenderId: '106683741204',
    projectId: 'fasum-3a7b2',
    authDomain: 'fasum-3a7b2.firebaseapp.com',
    databaseURL: 'https://fasum-3a7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-3a7b2.firebasestorage.app',
    measurementId: 'G-VVLHSFSKYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmF9WTDmmkWEmUGJk_aqUVdRI23x77FRM',
    appId: '1:106683741204:android:9289b0e7b20e4307a76301',
    messagingSenderId: '106683741204',
    projectId: 'fasum-3a7b2',
    databaseURL: 'https://fasum-3a7b2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fasum-3a7b2.firebasestorage.app',
  );
}
