// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSj0syS4YOsy7Ox5fkksMDt_FYlONGmSo',
    appId: '1:333195091288:web:201029d027466c43bb592d',
    messagingSenderId: '333195091288',
    projectId: 'app-first-7ee27',
    authDomain: 'app-first-7ee27.firebaseapp.com',
    databaseURL: 'https://app-first-7ee27-default-rtdb.firebaseio.com',
    storageBucket: 'app-first-7ee27.firebasestorage.app',
    measurementId: 'G-9B7BWP4R9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKcy4dP2yU9tIYqDqOoWQZPJ5mEmRxjCs',
    appId: '1:333195091288:android:0abe54b3601b5127bb592d',
    messagingSenderId: '333195091288',
    projectId: 'app-first-7ee27',
    databaseURL: 'https://app-first-7ee27-default-rtdb.firebaseio.com',
    storageBucket: 'app-first-7ee27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSj0syS4YOsy7Ox5fkksMDt_FYlONGmSo',
    appId: '1:333195091288:web:db649c1ba667a6adbb592d',
    messagingSenderId: '333195091288',
    projectId: 'app-first-7ee27',
    authDomain: 'app-first-7ee27.firebaseapp.com',
    databaseURL: 'https://app-first-7ee27-default-rtdb.firebaseio.com',
    storageBucket: 'app-first-7ee27.firebasestorage.app',
    measurementId: 'G-MTXTFPLY8R',
  );
}
